project:
  type: website
  output-dir: docs

website:
  title: "johnvasconcelos.github.io"
  description: "Public accountability and oversight"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: assign01_Data_Visualization.qmd
        text: Assig 01 Data Visualization
      - href: assign02_Data_Visualization
        text: Assig 02 Data Visualization
      - href: assign02_Data_Collection.qmd
        text: Assig 02 Data Collection  
      - href: assign03_Data_Collection.qmd
        text: Assig 03 Data Collection       
    right:
    - icon: github
      href: https://github.com/johnvasconcelos
    - icon: envelope
      href: mailto:you@utdallas.edu     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

