project:
  type: website
  output-dir: docs

website:
  title: "johnvasconcelos.github.io"
  description: "Public accountability and oversight"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - href: assign02.qmd
        text: Assignment 02
    right:
    - icon: github
      href: https://github.com/johnvasconcelos
    - icon: envelope
      href: mailto:you@utdallas.edu     

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

