project:
  type: website
  output-dir: docs

website:
  title: "John Vasconcelos"
  description: "Public accountability and oversight"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
      - text: EPPS 6356
        menu:
          - href: assign01_Data_Visualization.qmd
            text: Assignment 01
          - href: assign02_Data_Visualization.qmd
            text: Assignment 02
          - href: assign03_Data_Visualization.qmd
            text: Assignment 03
      - text: EPPS 6302
        menu:
          - href: assign02_Data_Collection.qmd
            text: Assignment 02
          - href: assign03_Data_Collection.qmd
            text: Assignment 03
    right:
      - icon: github
        href: https://github.com/johnvasconcelos
      - icon: envelope
        href: mailto:you@utdallas.edu

format:
  html:
    theme:
      darkly	      
    css: styles.css
    toc: true

execute:
  freeze: auto

editor: visual