---
format: html
editor: visual
execute:
  warning: false
  message: false
---

# Assignment EPPS 6355 - Grammar of Graphics

___

## Big data analytics pitfalls

Google Flu Trends (GFT) sought to detect surges of flu about one to two weeks brefore CDC, based on searches associated with this disease. The model in the beginning followed the CDC data very closely and was very successful. However, the expectation of continuously representing the data with accuracy never became real. GFT did not detect the 2009 H1N1 pandemic and overstimaed the incidence of flu by more than 199 weeds, and predicted more than double the medical appointments recorded by CDC for the 2012-2 seasons.

The failure is supposed to be due to a few factors. The "big data rubris" is the false presumption that big data can ultimately replace traditional monitoring. Google searches may reflect the concern of users regarding the sickness but not the sickness itself. Also, Google keeps changing its algorithms continuously, which must have caused relevant change to the way data is collected and classified. Also, one of the major problmes is that Google was not transparent and never published the terms it used for prediction, making it harder for researchers to validate the consistency of the method.

One example based on my own professional background as a former public sector auditor, is that our whitleblower line received a massive number of manifestations everyday, but most of them were not useful for auditing and fraud detection since most of the files were just citizens complaining about the government or services providade, never giving any useful information on whether there was some kind of fraud, where it was happening, who performed it etc. We had big data, but the data and its collection procedures were not designed to model the data according to our analytical needs.

___

## Overfitting and overparameterization

In my understanding, overfitting occurs whenever a model learns not only the pattern but also the noice of the data in the training dataset. It is good to describe the current data, but bad to predict new ones. Overparametrization is when the model has so many tentative parameters that almost any series can be explained. GFT shows both concepts. With so many parameters, some terms will inevitably correlate with flu by chance. The model ends up trying to explain even what should not be explained.

___

## Wickham talk summary

The lecture titled Data Visualization and data Science, by Hadley Wickham, discussed the importance of visualizing data in any modern data workflow. Wickham addresses the data analysis cycle (loading data, cleansing data, transofrming, visualizing, modeling and reporting) and emphasizes that data viz should not only be used for final reporting but it is a crucial stage for exploratory analysis itself. It allows for the user to find patterns and anomalies, and to see the strucuture of the data that can not be seen from tabular data. Ascombe's quartet is a classic example of it.

He also discussed the importance of the availability of tools such as R and the Tidyverse and Ggplot2 libraries, that are efficient and easy to implement, which relieves the cognitive toll on analysts, allowing for closer focus on problem resolution instead of worrying about handlingthe software and other implementations issues.
