---
title: "Research"
---

## Working Papers

**Machine Learning applied to Public Sector Auditing: A case study with data from the department of health of the state of São Paulo, Brazil**

> Abstract:
>
> Machine Learning (ML), as a field of Artificial Intelligence (AI), has become increasingly popular due to its ease of learning, scalability, and low cost. Both industry and academia have researched useful and feasible ways to apply ML algorithms for practical use in multiple fields, both academic and professional, taking advantage of their ability to learn patterns to predict future variables, classify or group data, and detect anomalous observations. Although the private sector has quickly evolved in studying the application of ML to financial fraud, stock market modeling and financial distress prediction, the application of these techniques in the public sector, namely in public audit, still demands further research for practical use. In this paper, I conduct a review of the current literature on machine learning applications for management-related fields and propose a case study to advance its application to public audit. I identified the Isolation Forest (iForest) algorithm as one of the most effective, scalable, and recognized for detecting anomalies. I applied it to a dataset with expenditure data from the Department of Health of the city of São Paulo, Brazil, and found that the algorithm can be of practical use for anomalous transaction value detection, but ineffective in identifying expenditure misclassification. The paper contributes to the scarce literature on the application of ML to public audit and seeks to promote further investigation for public oversight and improved management.

## Publications

Coming soon...
